### ISSUE TITLE
Invalid Token 에러 

### ISSUE THREAD

**Issue by dev-Lena** [SimLeeTag/Team#16]
Apple OAuth 로그인 후 모든 요청 header에 토큰 값을 담아서 요청.
-> 로그인을 할 때 invalid token이라고 401에러

![image](https://user-images.githubusercontent.com/52783516/102314568-070fb600-3fb6-11eb-8497-97561ec851d6.png)

**Comment by suhyunsim** [comment]
### 문제 상황
* 로그인하지 않은 유저가 API 요청을 보낼 시 토큰을 검증하는 인터셉터 로직에서 invalid token으로 요청 거절
* 인터셉터 등 백엔드 로직에는 문제 없이 제대로 예외처리를 하는 상황 -> 즉, **애초에 로그인이 제대로 이루어지지 않았음.**
* 로그인이 제대로 되지 않았던 이유
    * 로그인 요청 시 엔드포인트 오타(POST {base url}/apple-login을 applelogin으로 오타)
    * iOS와 BE가 공유하는 api 명세서와 swagger 문서의 내용이 다르게 기술되어 있었음(스프레드 시트: applelogin / swagger 문서: apple-login)

### 그 외 참고할 Photo Tag의 OAuth 동작 방식
* [Poogle 블로그 - Apple OAuth 백엔드 동작 포스트 링크](https://suhyunsim.github.io/2020-10-31/apple-oauth)
* Apple Login 시 Apple에서 발급한 토큰을 사용 (BE에서 토큰을 생성하는 것이 아님)

**Comment by dev-Lena** [comment]
확인했습니다! 감사합니다 :) 👍🏻👍🏻👍🏻

해당 에러 해결했습니다 (관련 이슈: [[Trouble] 네트워크 에러 invalid token 401](https://github.com/SimLeeTag/photo-tag-iOS/issues/27#issuecomment-735698824))

문제 해결로 이슈 클로즈하겠습니다!
