### ISSUE TITLE
현황 공유 및 2020-12-16 회의록

### ISSUE THREAD

**Issue by dev-Lena** [SimLeeTag/Team#18]
[레나]
* 지금까지의 현황 공유:
  - 지난 한달 동안 UI관련, 화면 전환, 네트워크 관련 클래스 구현 완료
  - 이팩티브 스위프트 스터디
  - 태그 관리 화면 구현 완료
* 계획:
  - 오늘부터 태그 카테고리 들어갑니다
  - 태그 카테고리는 UI만 먼저 구현. 다음으로 노트 추가 수정 삭제 구현. 
  7, 8번 API 구현이 끝나면 태그 카테고리 네트워크 연결

[푸글]
* 현황:
  - 2, 7, 8, 9, 12번 API 제외 포토태그 개발 완료 (API 문서 참고)
  - 지난 한달 동안 42Seoul Piscine 과정
* 계획:
오늘 7, 8번 API (태그 카테고리, 태그 별 노트 목록) 끝낼 예정 -> 사진 부분만 제외하고는 7번은 끝난 상황

**Comment by suhyunsim** [comment]
확인했습니다! 12월도 화이티잉
