### ISSUE TITLE
태그 카테고리 (7번 API) - 태그 정렬 관련 논의 사항

### ISSUE THREAD

**Issue by suhyunsim** [SimLeeTag/Team#19]
### 기존 협의 사항
* [BE issue 링크](https://github.com/SimLeeTag/photo-tag-backend/issues/21)
* 최근 사용된 Tag를 우선으로 정렬해서 보여주는 방식
* BE 구현 예상 방법:
    1. 태그 목록 전체를 훑어서 해당 유저의 활성된 태그들을 찾기
    2. 각각의 태그 마다 최근 사용된 노트를 찾아서 해당 노트의 첫 번째 사진을 찾기
    3. 태그의 정보들 + 각 태그에 해당되는 이미지 한 장을 한 덩어리로 생각해서 다시 최신 순서로 정렬하기
* 문제점:
    * 태그 자체적으로 생성/수정하는 기능이 없어서 태그는 시간에 관한 데이터를 갖고 있지 않음
    * 즉, 최근 사용된 태그를 확인하기 위해 노트 테이블에서 노트의 생성/수정 시간을 확인하고 그 노트에 사용된 태그들을 최신순으로 정렬해야 함

### 변경 사항
* 해당 문제를 해결할 좋은 방법을 알아내지 못했기 때문에 태그를 A-zㄱ-ㅎ 순서로 정렬하기로 결정

**Comment by dev-Lena** [comment]
확인했습니다!
* 기존: 태그 카테고리 API(7번 API)에서 해시태그 데이터를 최근에 사용된 순서로 정렬하여 제공
* 변경 후: 해시태그 데이터를 a-z ㄱ-ㅎ  순서로 정렬하여 제공

이렇게 알고 있겠습니다 👍 

❓🤔 그러면 영어 태그와 한글 태그가 둘 다 있을 경우 있을 때 영어로 된 태그가 더 먼저오는건가요?

**Comment by suhyunsim** [comment]
* a-zㄱ-ㅎ 순서로 정렬되는 것 맞습니다! 영문-한글 순서입니다.
* 태그의 썸네일이미지의 경우 태그를 사용한 가장 최신 노트의 사진 한장을 가져옵니다!

**Comment by dev-Lena** [comment]
아 그렇군요 감사합니다! 👍 

이슈 확인 완료했으니 클로즈하겠습니다!

**Comment by suhyunsim** [comment]
### 7번 API 명세서 최종 수정 상태
![Screenshot from 2020-12-22 14-11-01](https://user-images.githubusercontent.com/58318786/102851576-8fcb9d80-445f-11eb-884f-264369a0edfc.png)

* 논의한 내용
    * limit과 offset로 초기 설정한 파라미터는 size와 page의 이름으로 변경
    * 태그 이름 순으로 전체 정렬하기 위해 파라미터에 sort=tagName을 추가
    * Response로 사진 데이터를 전달할 때  thumbnail이라는 key를 사용하도록 변경
    * 노트를 생성하지 않은 초기 상태의 경우 전달될 태그 정보가 존재하지 않기 때문에 `[]`이렇게 빈 배열 하나만 전달
